steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - 'apply'
      - '-f'
      - 'k8s-deployment.yaml'
    env: 
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=nikhil-cluster'

images:
  - 'gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA'
