apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA  # This will use the image built by Cloud Build
        ports:
        - containerPort: 80  # Adjust this if your app uses a different port
